# Generated by Django 5.2.17 on 2026-09-14 18:19

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='código')),
                ('serial', models.CharField(blank=True, max_length=100, verbose_name='número de série')),
                ('photo', models.ImageField(blank=True, upload_to='assets/%Y/%m/', verbose_name='foto')),
                ('acquired', models.DateField(blank=True, null=True, verbose_name='data de aquisição')),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='valor de compra (R$)')),
                ('condition', models.CharField(default='Bom', max_length=200, verbose_name='conservação')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('total', models.PositiveIntegerField(default=0, editable=False)),
            ],
            options={
                'verbose_name': 'equipamento / lote',
                'ordering': ['product__category__name', 'location__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'categoria',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='contato')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'verbose_name': 'cliente',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Kit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'localização',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome do evento')),
                ('place', models.CharField(max_length=250, verbose_name='local do evento')),
                ('contact', models.CharField(blank=True, max_length=200, verbose_name='contato no local')),
                ('withdrawal', models.DateTimeField(verbose_name='retirada')),
                ('assembly', models.DateTimeField(verbose_name='montagem')),
                ('start', models.DateTimeField(verbose_name='início')),
                ('end', models.DateTimeField(verbose_name='término')),
                ('expected_return', models.DateTimeField(verbose_name='retorno previsto')),
                ('release', models.DateTimeField(verbose_name='liberação prevista após conferência')),
                ('status', models.CharField(choices=[('draft', 'Rascunho'), ('reserved', 'Reservado'), ('picking', 'Em separação'), ('out', 'Em operação'), ('checking', 'Aguardando conferência'), ('done', 'Concluído'), ('cancelled', 'Cancelado')], default='draft', editable=False, max_length=15)),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.client', verbose_name='cliente')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='managed_events', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('team', models.ManyToManyField(blank=True, related_name='assigned_events', to=settings.AUTH_USER_MODEL, verbose_name='equipe')),
            ],
            options={
                'verbose_name': 'evento',
                'ordering': ['withdrawal'],
            },
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=60)),
                ('quantity', models.IntegerField(default=0)),
                ('detail', models.TextField()),
                ('photo', models.ImageField(blank=True, upload_to='occurrences/%Y/%m/')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.asset')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.event')),
            ],
            options={
                'ordering': ['-at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='EventLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('separated', models.PositiveIntegerField(default=0)),
                ('sent', models.PositiveIntegerField(default=0)),
                ('returned', models.PositiveIntegerField(default=0)),
                ('cleared', models.PositiveIntegerField(default=0)),
                ('written_off', models.PositiveIntegerField(default=0)),
                ('sources', models.JSONField(default=list)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.asset')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='inventory.event')),
            ],
            options={
                'ordering': ['asset__product__category__name', 'asset__location__name', 'asset__code'],
            },
        ),
        migrations.AddField(
            model_name='asset',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.location', verbose_name='localização'),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('kind', models.CharField(choices=[('preventive', 'Preventiva'), ('corrective', 'Corretiva')], max_length=15, verbose_name='tipo')),
                ('reason', models.TextField(verbose_name='defeito / motivo')),
                ('provider', models.CharField(max_length=200, verbose_name='responsável / prestador')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('expected', models.DateField(blank=True, null=True, verbose_name='previsão')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='custo (R$)')),
                ('photo', models.ImageField(blank=True, upload_to='maintenance/%Y/%m/', verbose_name='foto / anexo')),
                ('closed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('final_condition', models.TextField(blank=True, editable=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance', to='inventory.asset', verbose_name='equipamento')),
            ],
            options={
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('kind', models.CharField(choices=[('unit', 'Individual'), ('bulk', 'Por quantidade'), ('supply', 'Consumível')], max_length=10, verbose_name='controle')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='marca')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('minimum', models.PositiveIntegerField(default=0, verbose_name='estoque mínimo')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'modelo de equipamento',
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KitComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='quantidade')),
                ('kit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='components', to='inventory.kit')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='modelo')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='modelo'),
        ),
        migrations.AddConstraint(
            model_name='event',
            constraint=models.CheckConstraint(condition=models.Q(('withdrawal__lte', models.F('assembly')), ('assembly__lte', models.F('start')), ('start__lt', models.F('end')), ('end__lte', models.F('expected_return')), ('expected_return__lte', models.F('release'))), name='ordered_event_dates'),
        ),
        migrations.AddConstraint(
            model_name='eventline',
            constraint=models.UniqueConstraint(fields=('event', 'asset'), name='unique_event_asset'),
        ),
        migrations.AddConstraint(
            model_name='eventline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('separated__lte', models.F('quantity')), ('sent__lte', models.F('separated')), ('returned__lte', models.F('sent')), ('cleared__lte', models.F('returned')), ('written_off__lte', django.db.models.expressions.CombinedExpression(models.F('sent'), '-', models.F('cleared'))), ('returned__lte', django.db.models.expressions.CombinedExpression(models.F('sent'), '-', models.F('written_off')))), name='consistent_line_counts'),
        ),
        migrations.AddConstraint(
            model_name='maintenance',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('cost__gte', 0)), name='valid_maintenance'),
        ),
        migrations.AddConstraint(
            model_name='kitcomponent',
            constraint=models.UniqueConstraint(fields=('kit', 'product'), name='unique_kit_product'),
        ),
        migrations.AddConstraint(
            model_name='kitcomponent',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='kit_positive'),
        ),
    ]
