# Generated by Django 5.2.17 on 2026-09-14 18:23

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventline',
            name='consistent_line_counts',
        ),
        migrations.AddField(
            model_name='eventline',
            name='waived',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name='eventline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('separated__lte', models.F('quantity')), ('sent__lte', models.F('separated')), ('waived__lte', django.db.models.expressions.CombinedExpression(models.F('quantity'), '-', models.F('sent'))), ('returned__lte', models.F('sent')), ('cleared__lte', models.F('returned')), ('written_off__lte', django.db.models.expressions.CombinedExpression(models.F('sent'), '-', models.F('cleared'))), ('returned__lte', django.db.models.expressions.CombinedExpression(models.F('sent'), '-', models.F('written_off')))), name='consistent_line_counts'),
        ),
    ]
