# Generated by Django 5.2.17 on 2026-09-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_eventline_consistent_line_counts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSequence',
            fields=[
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='audit',
            name='request_key',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
